### ISSUE TITLE
undefined method `inherits' for Chef::Resource::Directory when using chef_client_scheduled_task

### ISSUE THREAD

**Issue by damacus** [chef/chef#10023]
## Description

When using chef_client_scheduled_task with the following config

```yml
# server.yml
resources:
  - type: "chef_client_scheduled_task"
    name: Schedule Chef client
    accept_chef_license: true
    frequency: hourly
```

The following error occurs
```ruby
undefined method `inherits' for Chef::Resource::Directory 
```

## Chef Version

```bash
/opt/chef/bin/chef-client --version
Chef Infra Client: 16.2.4
```

## Platform Version

`Ubuntu 20.04`

## Replication Case

Create the following files:

```yml
# recipes/server.yml
resources:
  - type: "chef_client_scheduled_task"
    name: Schedule Chef client
    accept_chef_license: true
    frequency: hourly
```

```ruby
# recipes/default.rb
include_recipe 'test::server'
```

Run with chef-run

`chef-run test@test recipes/default.rb`

## Client Output

```bash
$ chef-run ubuntu@<ip-address> recipes/default.rb
[✔] Packaging cookbook... done!
[✔] Generating local policyfile... exporting... done!
[✖] Applying chef_pi::default from <cookbook_directory> to target.
└── [✖] [<ip-address>] Failed to converge chef_pi::default.

The converge of the remote host failed for the
following reason:

  undefined method `inherits' for Chef::Resource::Directory
```

## Stacktrace

No stack trace
