### ISSUE TITLE
Mount resource changes broke specs on AIX

### ISSUE THREAD

**Issue by tas50** [chef/chef#10635]
The changes to the mount resource have broken aix tests, which are causing build failures.

```

Failures:



  1) Chef::Resource::Mount when the target state is a mounted filesystem should mount the filesystem if it isn't mounted

     Failure/Error: new_resource.run_action(:mount)



     Chef::Exceptions::Mount:

       mount[/tmp/cheftest/testmount20201111-30277666-d32unt] (dynamically defined) had an error: Chef::Exceptions::Mount: Device / does not exist

     # ./lib/chef/provider/mount/mount.rb:46:in `mountable?'

     # ./lib/chef/provider/mount/aix.rb:123:in `mount_fs'

     # ./lib/chef/provider/mount.rb:41:in `block (2 levels) in <class:Mount>'

     # ./lib/chef/mixin/why_run.rb:51:in `add_action'

     # ./lib/chef/provider.rb:265:in `converge_by'

     # ./lib/chef/provider/mount.rb:40:in `block in <class:Mount>'

     # (eval):2:in `block in action_mount'

     # ./lib/chef/provider.rb:276:in `instance_eval'

     # ./lib/chef/provider.rb:276:in `compile_and_converge_action'

     # (eval):2:in `action_mount'

     # ./lib/chef/provider.rb:217:in `run_action'

     # ./lib/chef/resource.rb:599:in `block in run_action'

     # ./lib/chef/resource.rb:626:in `with_umask'

     # ./lib/chef/resource.rb:598:in `run_action'

     # ./spec/functional/resource/mount_spec.rb:159:in `block (3 levels) in <top (required)>'

     # ./spec/spec_helper.rb:305:in `block (2 levels) in <top (required)>'

     # ------------------

     # --- Caused by: ---

     # Chef::Exceptions::Mount:

     #   Device / does not exist

     #   ./lib/chef/provider/mount/mount.rb:46:in `mountable?'



  2) Chef::Resource::Mount when the filesystem should be remounted and the resource supports remounting should remount the filesystem if it is mounted

     Failure/Error: new_resource.run_action(:mount)



     Chef::Exceptions::Mount:

       mount[/tmp/cheftest/testmount20201111-30277666-d32unt] (dynamically defined) had an error: Chef::Exceptions::Mount: Device / does not exist

     # ./lib/chef/provider/mount/mount.rb:46:in `mountable?'

     # ./lib/chef/provider/mount/aix.rb:123:in `mount_fs'

     # ./lib/chef/provider/mount.rb:41:in `block (2 levels) in <class:Mount>'

     # ./lib/chef/mixin/why_run.rb:51:in `add_action'

     # ./lib/chef/provider.rb:265:in `converge_by'

     # ./lib/chef/provider/mount.rb:40:in `block in <class:Mount>'

     # (eval):2:in `block in action_mount'

     # ./lib/chef/provider.rb:276:in `instance_eval'

     # ./lib/chef/provider.rb:276:in `compile_and_converge_action'

     # (eval):2:in `action_mount'

     # ./lib/chef/provider.rb:217:in `run_action'

     # ./lib/chef/resource.rb:599:in `block in run_action'

     # ./lib/chef/resource.rb:626:in `with_umask'

     # ./lib/chef/resource.rb:598:in `run_action'

     # ./spec/functional/resource/mount_spec.rb:170:in `block (3 levels) in <top (required)>'

     # ./spec/spec_helper.rb:305:in `block (2 levels) in <top (required)>'

     # ------------------

     # --- Caused by: ---

     # Chef::Exceptions::Mount:

     #   Device / does not exist

     #   ./lib/chef/provider/mount/mount.rb:46:in `mountable?'



  3) Chef::Resource::Mount when the target state is a unmounted filesystem should umount the filesystem if it is mounted

     Failure/Error: new_resource.run_action(:mount)



     Chef::Exceptions::Mount:

       mount[/tmp/cheftest/testmount20201111-30277666-d32unt] (dynamically defined) had an error: Chef::Exceptions::Mount: Device / does not exist

     # ./lib/chef/provider/mount/mount.rb:46:in `mountable?'

     # ./lib/chef/provider/mount/aix.rb:123:in `mount_fs'

     # ./lib/chef/provider/mount.rb:41:in `block (2 levels) in <class:Mount>'

     # ./lib/chef/mixin/why_run.rb:51:in `add_action'

     # ./lib/chef/provider.rb:265:in `converge_by'

     # ./lib/chef/provider/mount.rb:40:in `block in <class:Mount>'

     # (eval):2:in `block in action_mount'

     # ./lib/chef/provider.rb:276:in `instance_eval'

     # ./lib/chef/provider.rb:276:in `compile_and_converge_action'

     # (eval):2:in `action_mount'

     # ./lib/chef/provider.rb:217:in `run_action'

     # ./lib/chef/resource.rb:599:in `block in run_action'

     # ./lib/chef/resource.rb:626:in `with_umask'

     # ./lib/chef/resource.rb:598:in `run_action'

     # ./spec/functional/resource/mount_spec.rb:183:in `block (3 levels) in <top (required)>'

     # ./spec/spec_helper.rb:305:in `block (2 levels) in <top (required)>'

     # ------------------

     # --- Caused by: ---

     # Chef::Exceptions::Mount:

     #   Device / does not exist

     #   ./lib/chef/provider/mount/mount.rb:46:in `mountable?'



  4) Chef::Resource::Mount when enabling the filesystem to be mounted should enable the mount if it isn't enable

     Failure/Error: new_resource.run_action(:mount)



     Chef::Exceptions::Mount:

       mount[/tmp/cheftest/testmount20201111-30277666-d32unt] (dynamically defined) had an error: Chef::Exceptions::Mount: Device / does not exist

     # ./lib/chef/provider/mount/mount.rb:46:in `mountable?'

     # ./lib/chef/provider/mount/aix.rb:123:in `mount_fs'

     # ./lib/chef/provider/mount.rb:41:in `block (2 levels) in <class:Mount>'

     # ./lib/chef/mixin/why_run.rb:51:in `add_action'

     # ./lib/chef/provider.rb:265:in `converge_by'

     # ./lib/chef/provider/mount.rb:40:in `block in <class:Mount>'

     # (eval):2:in `block in action_mount'

     # ./lib/chef/provider.rb:276:in `instance_eval'

     # ./lib/chef/provider.rb:276:in `compile_and_converge_action'

     # (eval):2:in `action_mount'

     # ./lib/chef/provider.rb:217:in `run_action'

     # ./lib/chef/resource.rb:599:in `block in run_action'

     # ./lib/chef/resource.rb:626:in `with_umask'

     # ./lib/chef/resource.rb:598:in `run_action'

     # ./spec/functional/resource/mount_spec.rb:197:in `block (3 levels) in <top (required)>'

     # ./spec/spec_helper.rb:305:in `block (2 levels) in <top (required)>'

     # ------------------

     # --- Caused by: ---

     # Chef::Exceptions::Mount:

     #   Device / does not exist

     #   ./lib/chef/provider/mount/mount.rb:46:in `mountable?'



  5) Chef::Resource::Mount when the target state is to disable the mount should disable the mount if it is enabled

     Failure/Error: new_resource.run_action(:mount)



     Chef::Exceptions::Mount:

       mount[/tmp/cheftest/testmount20201111-30277666-d32unt] (dynamically defined) had an error: Chef::Exceptions::Mount: Device / does not exist

     # ./lib/chef/provider/mount/mount.rb:46:in `mountable?'

     # ./lib/chef/provider/mount/aix.rb:123:in `mount_fs'

     # ./lib/chef/provider/mount.rb:41:in `block (2 levels) in <class:Mount>'

     # ./lib/chef/mixin/why_run.rb:51:in `add_action'

     # ./lib/chef/provider.rb:265:in `converge_by'

     # ./lib/chef/provider/mount.rb:40:in `block in <class:Mount>'

     # (eval):2:in `block in action_mount'

     # ./lib/chef/provider.rb:276:in `instance_eval'

     # ./lib/chef/provider.rb:276:in `compile_and_converge_action'

     # (eval):2:in `action_mount'

     # ./lib/chef/provider.rb:217:in `run_action'

     # ./lib/chef/resource.rb:599:in `block in run_action'

     # ./lib/chef/resource.rb:626:in `with_umask'

     # ./lib/chef/resource.rb:598:in `run_action'

     # ./spec/functional/resource/mount_spec.rb:205:in `block (3 levels) in <top (required)>'

     # ./spec/spec_helper.rb:305:in `block (2 levels) in <top (required)>'

     # ------------------

     # --- Caused by: ---

     # Chef::Exceptions::Mount:

     #   Device / does not exist

     #   ./lib/chef/provider/mount/mount.rb:46:in `mountable?'
```
