### ISSUE TITLE
Windows integration test failures

### ISSUE THREAD

**Issue by tas50** [chef/chef#11426]
```
Failures:

  1) chef-solo when the chef repo has a cookbook with an undeclared dependency should exit with an error
     Failure/Error: expect(result.exitstatus).to eq(0) # For CHEF-5120 this becomes 1

       expected: 0
            got: 3

       (compared using ==)
     # ./spec/integration/solo/solo_spec.rb:120:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:303:in `block (2 levels) in <top (required)>'

  2) chef-solo when the chef repo has a cookbook with an incompatible ohai_version should exit with an error
     Failure/Error: expect(result.exitstatus).to eq(1)

       expected: 1
            got: 3

       (compared using ==)
     # ./spec/integration/solo/solo_spec.rb:154:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:303:in `block (2 levels) in <top (required)>'
```

https://buildkite.com/chef/chef-chef-master-omnibus-release/builds/1186#39d32184-68ea-4ff4-a56c-e0821b4b736e
