### ISSUE TITLE
Compliance Phase not working with vendor InSpec profiles from Chef Automate

### ISSUE THREAD

**Issue by collinmcneese** [chef/chef#12558]
## Description

A common practice with InSpec profile authoring is to use the wrapper methodology and use a profile sourced from Chef Automate as the dependency since these profiles that ship with Automate, such as CIS benchmarks, are kept up-to-date within Automate so a wrapper profile can call controls from a wrapped profile and make adjustments as needed.

When running Compliance Phase ( Chef Infra Client 17.9.42) and using an embedded Chef InSpec profile within a cookbook, Compliance Phase is unable to properly run an InSpec profile which has a dependency on a profile which uses `compliance` (Chef Automate) as a source.

```
[2022-02-04T20:28:40+00:00] ERROR: Chef InSpec has raised a runtime exception. Generating a minimal failed report.
[2022-02-04T20:28:40+00:00] ERROR: undefined method `[]' for nil:NilClass
```

Fetching profiles from other sources, such as `url` and `git`, works as expected, however attempts to fetch profiles from Chef Automate, either using the `chef-server`  or `chef-automate` fetcher methods will result in an error.

- Vendor profile from url source (works):

```yaml
depends:
- name: linux-patch-baseline
  url: https://github.com/dev-sec/linux-patch-baseline/archive/refs/heads/master.zip
```

- Vendor profile from Automate (produces error):

```yaml
depends:
- name: cis-amazonlinux2-level2
  compliance: admin/cis-amazonlinux2-level2
```

## Chef Version

17.9.42

## Platform Version

Amazon Linux 2

## Replication Case

- Create a cookbook which has a local profile under `compliance/profiles`
- Add a dependency on a profile from Chef Automate in the `inspec.yml` file
```yaml
  depends:
- name: cis-amazonlinux2-level2
  compliance: admin/cis-amazonlinux2-level2 
```
- Make sure that client is configured to communicate with Chef Automate, either directly or via Chef Infra Server
- Run a client converge, attempting to trigger Compliance Phase to execute the local profile which calls a dependency from Chef Automate

## Client Output

The following error will show during a run at default logging levels:

```
[2022-02-04T20:28:40+00:00] ERROR: Chef InSpec has raised a runtime exception. Generating a minimal failed report.
[2022-02-04T20:28:40+00:00] ERROR: undefined method `[]' for nil:NilClass
```

With trace logging set, we can see that it _does_ fetch the profile from Chef Automate and it copies this to `/root/.inspec/cache` as well:

```
[2022-02-04T20:28:40+00:00] TRACE: Streaming download from https://chef-infra-FQDN/compliance/organizations/a2local/owners/admin/compliance/cis-amazonlinux2-level2/tar to tempfile /tmp/chef-rest20220204-32234-asga9c
[2022-02-04T20:28:40+00:00] TRACE: content_encoding = ''               initializing noop stream deflator.
... truncated ...
[2022-02-04T20:28:40+00:00] TRACE: Chef::HTTP calling Chef::HTTP::JSONInput#handle_stream_complete
[2022-02-04T20:28:40+00:00] ERROR: Chef InSpec has raised a runtime exception. Generating a minimal failed report.
[2022-02-04T20:28:40+00:00] ERROR: undefined method `[]' for nil:NilClass
[2022-02-04T20:28:40+00:00] INFO: Reporting to chef-server-automate
```
