### ISSUE TITLE
windows_task command's arguments are missing when "notifies" is defined

### ISSUE THREAD

**Issue by hunter86bg** [chef/chef#13011]
## Description
When setting "notifies" to a windows_task , the command arguments are not processed (missing)

## Chef Version
Test system:
Windows 2012R2 with chef-client-17.10.3-1-x64.msi on it.

Client system (where chef-kitchen is executed):
Chef Workstation version: 22.6.973
Chef InSpec version: 4.56.20
Chef CLI version: 5.6.1
Chef Habitat version: 1.6.420
Test Kitchen version: 3.2.2
Cookstyle version: 7.32.1
Chef Infra Client version: 17.10.0

## Platform Version

Test system:
Windows 2012R2 with chef-client-17.10.3-1-x64.msi on it.

Client system (where chef-kitchen is executed):
Chef Workstation version: 22.6.973
Chef InSpec version: 4.56.20
Chef CLI version: 5.6.1
Chef Habitat version: 1.6.420
Test Kitchen version: 3.2.2
Cookstyle version: 7.32.1
Chef Infra Client version: 17.10.0

## Replication Case
1. Install Windows 2012R2 VHD from [Microsoft](https://go.microsoft.com/fwlink/p/?linkid=2195588&clcid=0x409&culture=en-us&country=us)
2. Activate Hyper-V on Windows 10 (21H2/ OS Build 19044.1766)
3. Create a new VM and attach the disk
4. Use default switch (if connectivity is broken , create an internal one)
5. Start the 2012R2, set a user and a password
6. Upload and install the chef-client (chef-client-17.10.3-1-x64.msi) on the 2012R2
7. Allow winrm from the client system (win10 21H2) over the IP:
```
Set-Item WSMan:\localhost\Client\TrustedHosts -Value '172.26.121.*'
```
8.Test winrm connectivity
```
$cred = Get-Credential
Enter-PSSession -Computername 172.26.121.31 -Authentication Negotiate -Credential $cred
```
9. Create cookbook & recipe
```
chef generate cookbook mycookbook
cd mycookbook
chef generate recipe myrecipe
```
10. Create recipe like this:
```
directory 'web_scripts' do
  inherits                   true
  mode                       '0777'
  path                       'C:\\scripts\\web\\'
  recursive                  true
  action                     :create
end

cookbook_file 'mypowershell_script.ps1' do
  atomic_update              true
  backup                     false
  inherits                   true
  mode                       '0777'
  path                       'C:\\scripts\\web\\mypowershell_script.ps1'
  source                     'mypowershell_script.ps1'
  action                     :create
  notifies                   :create, 'directory[web_scripts]', :before
end

windows_task 'webtask' do
  user 'SYSTEM'
  run_level :highest
  frequency :daily
  start_time '09:50'
  execution_time_limit 600 #This will be another bug, use integer only
  command 'powershell.exe -ExecutionPolicy Bypass -File "C:\\scripts\\web\\mypowershell_script.ps1"'
  guard_interpreter :powershell_script
  force true
  only_if 'Test-Path "C:\\scripts\\web\\mypowershell_script.ps1"'
  notifies :create, 'cookbook_file[mypowershell_script.ps1]', :before
end
```
11. Create kitchen's yml (replace IP, username and pass)
```
---
provisioner:
  name: chef_zero
  log_level: debug


verifier:
  name: inspec


platforms:
  - name: windows-2012R2
    os_type: windows
    shell_type: powershell
    transport:
      name: winrm
      elevated: true
      username: 'user'
      password: 'pass'
      hostname: 'ip_of_VM'
    driver:
      box: windows-2012r2


suites:
  - name: myrecipe
    run_list:
      - recipe[myrecipe]

```
12. Create a file in cookbook_dir/files that is named "mypowershell_script.ps1"
13. Execute kitchen 
```
kitchen converge -l debug
```
15. Verify the task on the  2012R2 system

 
## Client Output
https://gist.githubusercontent.com/hunter86bg/792e9fd79028b5dd54faa091564446fd/raw/c106e7f0d959729fd9cad1edf9edcddfe1b07645/gistfile1.txt

## Stacktrace
Kitchen completes successfully, so no stacktraces available

Workaround:
Comment "notifies" section of the windows_task .
