### ISSUE TITLE
`knife data bag show` does not respect relative paths in ~/.chef/credentials config file

### ISSUE THREAD

**Issue by drewhammond** [chef/chef#14473]
## Description

When using a relative path to `secret_file` in `~/.chef/credentials`, knife cannot find the file when it needs to open a data bag.

```toml
[default]
node_name = "myuser"
client_key = "myuser.pem" # ~/.chef/myuser.pem
chef_server_url = 'https://chef-server.example.com/organizations/example'

[default.knife]
ssh_user = 'example'
secret_file = 'my_databag_secret_file' # ~/.chef/my_databag_secret_file
```

According to [this documentation](https://docs.chef.io/workstation/knife_setup/), relative paths should work. I'd expect them to also work for this `secret_file` property.

>File paths, such as `client_key` or `validator_key`, are relative to `~/.chef` unless you provide absolute path. 

## Chef Version

```
➜  ~ cinc version
Cinc Workstation version: 24.4.1064
Cinc Auditor version: 5.22.40
Cinc CLI version: 5.6.14
Biome version: unknown
Test Kitchen version: 3.6.0
Cookstyle version: 7.32.8
Cinc Client version: 18.4.12
```

## Platform Version

MacOS 14.4.1 (23E224) - arm64

## Replication Case

1. Create databag secret file `~/.chef/my_databag_secret_file`
2. Reference it with a relative path in `~/.chef/credentials`, i.e. `secret_file = 'my_databag_secret_file'`
3. Run `knife data bag show foo bar`
4. Observe error

If you change the relative path to an absolute path, everything works fine. 

## Client Output

```
➜  ~ knife data bag show foo bar
ERROR: Errno::ENOENT: No such file or directory - file not found 'my_databag_secret_file'
```
