### ISSUE TITLE
Downloaded asset via remote_file on 12.0.1 does not match checksum that has been verified manually via curl + md5sum, plus verified working on 11.12.2

### ISSUE THREAD

**Issue by cparedes** [chef/chef#2614]
Issue:

Asset that's downloaded via remote_file on 12.0.1 doesn't seem to be downloading correctly. Checksum differs wildly to what is confirmed via manual curl as well as at least version 11.12.2.

Test environment:
- nginx cookbook version 2.7.4 using nginx::source
- test-kitchen 1.2.1
- CentOS 6.5 image on Vagrant pulled from Opscode repo

Reproduction steps:

Create a minimal kitchen environment:

.kitchen.yml:

```

---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: 12.0.1 # replace with '11.12.2' to test against a known good version
  use_vagrant_berkshelf_plugin: true
  customize:
    memory: 1536
    cpus: 2

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list: recipe[nginx::source]
```

Berksfile:

```
source 'https://supermarket.chef.io'

cookbook 'nginx'
```

Run test kitchen setup:

```
kitchen setup
```

Error when using 12.0.1:

```
* remote_file[http://nginx.org/download/nginx-1.4.4.tar.gz] action create[2014-12-11T00:51:38+00:00] INFO: Processing remote_file[http://nginx.org/download/nginx-1.4.4.tar.gz] action create (nginx::source line 58)


           ================================================================================
           Error executing action `create` on resource 'remote_file[http://nginx.org/download/nginx-1.4.4.tar.gz]'
           ================================================================================

           Chef::Exceptions::ChecksumMismatch
           ----------------------------------
           Checksum on resource (0510af) does not match checksum on content (7c989a)

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/nginx/recipes/source.rb

            58: remote_file nginx_url do
            59:   source   nginx_url
            60:   checksum node['nginx']['source']['checksum']
            61:   path     src_filepath
            62:   backup   false
            63: end
            64:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/nginx/recipes/source.rb:58:in `from_file'

           remote_file("http://nginx.org/download/nginx-1.4.4.tar.gz") do
             provider Chef::Provider::RemoteFile
             action "create"
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             path "/tmp/kitchen/cache/nginx-1.4.4.tar.gz"
             atomic_update true
             source ["http://nginx.org/download/nginx-1.4.4.tar.gz"]
             use_etag true
             use_last_modified true
             cookbook_name "nginx"

         recipe_name "source"
             checksum "0510af71adac4b90484ac8caf3b8bd519a0f7126250c2799554d7a751a2db388"
           end
```

But remote_file downloads successfully with 11.12.2.
