### ISSUE TITLE
Could not load the 'chef-solo' provisioner from the load path

### ISSUE THREAD

**Issue by hlx98007** [chef/chef#4159]
I have this weird problem that Googling does not give me an answer.

I have freshly installed ChefDK and Chef Client on my CentOS 7 workstation, downloaded the starter kit and modified .kitchen.yml to follows:

```yml
---
driver:
  name: opennebula
  opennebula_endpoint: http://10.1.1.1/zonea
  oneauth_file: /home/local/.one/one_auth
  template_name: CHEF-TESTVM
  vm_hostname: CHEF-TESTVM-FRONT-END
  public_key_path: /home/local/.ssh/id_rsa.pub
  username: root
  memory: 4096
  require_chef_omnibus: false
  user_variables:
    FILEHOME: http://10.1.1.2/~dev/repo/

provisioner:
  name: chef-solo
  environments_path: /home/local/chef-repo/cookbooks/init/environments/
  role_path: /home/local/chef-repo/cookbooks/init/roles/

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    provisioner:
      solo_rb:
        environment: dev
    run_list:
      - recipe[wfe]
      - role[common]
    attributes:
```

 I ran `kitchen test` it gives the following message:
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'chef-solo' provisioner from the load path. Please ensure that your provisioner is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
```

`which chef-solo` returns `/opt/chefdk/bin/chef-solo`

I have already installed kitchen-opennebula and its dependencies.
