### ISSUE TITLE
Failure to post the audit report should not be an error when running from Test Kitchen

### ISSUE THREAD

**Issue by tpetchel** [chef/chef#4728]
## Description

When developing a cookbook for use with audit mode, you may want to first run it through Test Kitchen. You'll likely get an ERROR message when chef-client attempts to post the audit report to the  server:

```
[...]
       Synchronizing Cookbooks:
         - audit_web_rhel (0.1.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Starting audit phase

       Finished in 0.00021 seconds (files took 0.46834 seconds to load)
       0 examples, 0 failures
       Auditing complete

       Running handlers:
       Running handlers complete
       Chef Client finished, 0/0 resources updated in 01 seconds
       [2016-03-21T13:32:43+00:00] ERROR: Failed to post audit report to server. Saving report to /tmp/kitchen/cache/failed-audit-data.json
       Finished converging <default-centos-72> (0m22.46s).
-----> Kitchen is finished. (2m15.26s)
```

I feel that ERROR is not the correct severity for this case because I don't expect there to be a server. The ERROR leads me to believe that something failed in one of my audit controls.

Perhaps WARN or INFO would be more appropriate here, or skip the upload process if if we can detect that we're running through Test Kitchen.

## Chef Version

12.8.1

## Platform Version

Discovered on CentOS 7.2, but applies to any platform.

## Replication Case

Step 1: Create a cookbook.

```
$ chef generate cookbook TEST
```

Step 2: Modify .kitchen.yml to enable audit mode.

```
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :audit_only

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[TEST::default]
    attributes:
```

Step 3: Run `kitchen converge`.

```
$ kitchen converge
```

## Client Output

https://gist.github.com/tpetchel/69cc5f17692ec93e174b

## Stacktrace

N/A
