### ISSUE TITLE
Chef 13 vs Chef 12 ip address resolution

### ISSUE THREAD

**Issue by mickfeech** [chef/chef#6060]
## Description

There has been something that has changed in the way Chef handles IP address resolution from 13 vs 12.  I have a custom chef resource that utilizes Hashicorp's Vault Gem.  Anything with Chef 13 is failing with an IPAddr::InvalidAddressError

## Chef Version

Chef 13.0.118

## Platform Version

Linux RHEL 7.3

## Replication Case

``` secret.rb
resource_name :vault_secret
default_action :read
property :path, String, name_property: true
property :destination
action :read do
  Vault.address = node['vault_address']
  Vault.token = node['vault_token']
  destination ||= path
  secret = Vault.logical.read(path)
  if secret.nil?
    raise "Could not read secret `#{path}'!"
  end
  updated_by_last_action(true)
  node.run_state[destination] = secret
end
```

## Stacktrace

```
    docker: IPAddr::InvalidAddressError
    docker: ---------------------------
    docker: invalid address
    docker:
    docker: Cookbook Trace:
    docker: ---------------
    docker: /tmp/packer-chef/local-mode-cache/cache/cookbooks/hashivault/resources/secret.rb:9:in `block in class_from_file'
```
### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* Requests for new or alternative functionality should be made to [feedback.chef.io](https://feedback.chef.io/forums/301644-chef-product-feedback/category/110832-chef-client)
* [Chef Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)
