### ISSUE TITLE
Powershell Add-AppxPackage not working for standard user (only elevated admin)

### ISSUE THREAD

**Issue by jeremy-qik** [chef/chef#7765]
Hopefully this is the right place (sorry if its not). I am currently trying to side load an appx (UWP) in test kitchen. However it does not work for a standard user. When I set it to an admin account, it works (but that only installs the app for that admin user - I need it installed for a deescalated user). I suspect this is a bug in remote Powershell?

**Output:**
```ruby
STDERR: C:\Users\....\AppData\Local\Temp\chef-script20181023-3108-f0qjq7.ps1 : Win32 internal error "Access is denied" 0x5 
       
       occurred while reading the console output buffer. Contact Microsoft Customer Support Services.
```

**Code:**
```ruby
powershell_script 'Install Appx' do
     code 'Add-AppxPackage Example_1.0.0.0.appx'
     cwd 'C:\...'
     user "standardUserHere"
     password "password"
     sensitive false
end
```

**Comment by jeremy-qik** [comment]
Hi @stuartpreston 
Thanks for you response.
I have tried logging in as the standard user and running the commands in powershell manually and it works. 
---
If I change the user running in power shell to the admin (non elevated in the powershell_script it works).

e.g.
```
powershell_script 'Install Appx' do
     code 'Add-AppxPackage Example_1.0.0.0.appx'
     cwd 'C:\...'
     user "adminUser"
     password "adminPassword"
     sensitive false
end
```

---

**Runas**
```
PS C:\Users\adminUser> runas /user:'standardUser' “powershell”
runas /user:'standardUser' powershell
Enter the password for standardUser:
Attempting to start powershell as user "DESKTOP-...\standardUser" ...
```
(in the new Window that popped up)
```
PS C:\Windows\system32> whoami
desktop-...\standardUser
...(cd to dir)…
PS C:\Dir> Add-AppxPackage Example_1.0.0.0_x64.appx
```
And it works (`Get-AppxPackage -Name *Example*` reports app successfully installed) 

---

**.kitchen.yml**
```
---
driver:
  name: vagrant
  communicator: winrm

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  #log_level: info

verifier:
  name: inspec

transport:
  name: winrm
  guest: windows
  elevated: true

platforms:
  - name: windows
    os_type: windows
    driver:
      box: image_name_here
    driver_config:
      username: adminUser
      password: adminPass

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    run_list:
    - recipe[...]
    verifier:
    inspec_tests:
        - test/integration/default
```

I have tried various other configs permutations this morning to try and fix the issue and no luck (such as removing the elevated).

---

**Versions**

```
$ chef --version
Chef Development Kit Version: 3.2.30
chef-client version: 14.4.56
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.6
kitchen version: 1.23.2
inspec version: 2.2.70
```

```
$vagrant --version
Vagrant 2.0.4
```

```
Virtualbox: 5.2.18
```

**Comment by stuartpreston** [comment]
That is strange, as when you run with `elevated: true` Test Kitchen will create a scheduled task on the remote computer.  So this should mimic exactly Chef Client running as the specified user on the target machine.  Though usually Chef Client is running as System if installed as a Scheduled Task or even the Windows Service so perhaps you could try with adding:

```yml
elevated_username: System
elevated_password: null
```

**Comment by jeremy-qik** [comment]
I tried adding (below) but same issue. I also tried placing the elevated_username/elevated_password under driver_config as well

```
---
driver:
  name: vagrant
  communicator: winrm

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  #log_level: info

verifier:
  name: inspec

transport:
  name: winrm
  guest: windows
  elevated: true
  elevated_username: System
  elevated_password: null

platforms:
  - name: windows
    os_type: windows
    driver:
      box: image_name_here
    driver_config:
      username: adminUser
      password: adminPass

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    run_list:
    - recipe[...]
    verifier:
    inspec_tests:
        - test/integration/default
```

```
STDOUT: 
       STDERR: C:\Windows\Temp\chef-script20181024-5088-ld3fe7.ps1 : Win32 internal error "Access is denied" 0x5 occurred while 
       
       reading the console output buffer. Contact Microsoft Customer Support Services.
       
       
       ---- End output of "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Windows/Temp/chef-script20181024-5088-ld3fe7.ps1" ----
```
