### ISSUE TITLE
apt-keys call within apt_repository broken for debian >9.3

### ISSUE THREAD

**Issue by EugenMayer** [chef/chef#7913]
when installing a repo using apt_repository from debian >9.3 it will fail since tty is missing

using this kitchen setup for reproducing this:

```yaml
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  
verifier:
  name: inspec

platforms:
  - name: debian/stretch64
    driver:
      box: debian/stretch64
      box_version: "9.3.0"
  - name: debian/stretch64
    driver:
      box: debian/stretch64
      box_version: "9.4.0"
  - name: debian/stretch64
    driver:
      box: debian/stretch64
      box_version: "9.5.0"

suites:
  - name: default
    run_list:
    - recipe[chef-apt-docker::default]
```

For 9.3 it will work, for 9.4 / 9.5 it will fail with

```
 ---- End output of apt-key adv --recv --keyserver hkp://keyserver.ubuntu.com:80 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 ----
       Ran apt-key adv --recv --keyserver hkp://keyserver.ubuntu.com:80 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 returned 2
       [2018-11-10T22:01:37+00:00] ERROR: apt_repository[docker-stable] (chef-apt-docker::default line 29) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[install-key 9DC858229FC7DD38854AE2D88D81803C0EBFCD88] (/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.12.3/lib/chef/provider/apt_repository.rb line 194) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
       ---- Begin output of apt-key adv --recv --keyserver hkp://keyserver.ubuntu.com:80 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 ----
       STDOUT: Executing: /tmp/apt-key-gpghome.dVFKHp4W4m/gpg.1.sh --recv --keyserver hkp://keyserver.ubuntu.com:80 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
       STDERR: Warning: apt-key output should not be parsed (stdout is not a terminal)
       gpg: cannot open '/dev/tty': No such device or address
```

I would expect the critical part to be

```
gpg: cannot open '/dev/tty': No such device or address
```

Even though i use `chef-apt-docker::default` here, it would not really matter, they just add a `apt_repository` [like this](https://github.com/chef-cookbooks/chef-apt-docker/blob/master/recipes/default.rb#L29)

Talking to the `debian` people, they had a lot of upgrades on gpg in those releases, so that might be the case. it seems like the possible fix is adding `--no-tty` to add-keys would help.

If of any interested, using 

```console
apt-key adv --recv --keyserver hkp://keyserver.ubuntu.com:80 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
```
on the cli on that box which failed to converge using `chef exec kitchen login default` will work without issues, so its not a false positve
