### ISSUE TITLE
Missing VC++ files required for powershell_exec feature

### ISSUE THREAD

**Issue by stuartpreston** [chef/chef#8057]
## Description
Windows Server 2016 does not ship with a Visual C++ redistributable by default, leaving it to the package provider to ship a redistributable or the binaries in the base (bin) folder for compiled C++ code (e.g. Chef.PowerShell.Wrapper) to work

## Chef Version
14.8 

## Platform Version
Windows Server 2016 (and assumed 2019)

## Replication Case
cookbooks/mycookbook/default.rb
```ruby
outcome = powershell_exec("Get-WindowsFeature | where { $_.Installed -eq $true }")
if outcome.error?
  outcome.errors.each do |e|
    puts error e
  end
else
  puts "Result: #{outcome.result}"
end
```

```yml
---
driver:
  name: azurerm
  subscription_id: '43706c4e-YOUR-SUBS-CRIP-e64e6bf63ac4'
  location: 'West Europe'
  machine_size: 'Standard_D2_V2'

provisioner:
  name: chef_zero
  retry_on_exit_code:
    - 20
    - 35
  max_retries: 10
  wait_for_retry: 180
  client_rb:
    exit_status: :enabled

platforms:
  - name: windows2016
    driver:
      image_urn: MicrosoftWindowsServer:WindowsServer:2016-Datacenter:latest
    transport:
      name: winrm
      elevated: true

suites:
  - name: default
    run_list:
      - recipe[mycookbook::default]
    attributes:
```

## Client Output
```
C:\projects\repro\chefwrappertest> kitchen converge
-----> Starting Kitchen (v1.23.2)
-----> Converging <default-windows2016>...
       Preparing files for transfer
       Preparing dna.json
       Preparing cookbooks from project directory
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (install only if missing)
       Downloading package from https://packages.chef.io/files/stable/chef/14.8.12/windows/2016/chef-client-14.8.12-1-x64.msi

       resolving cookbooks for run list: ["mycookbook::default"]
       Synchronizing Cookbooks:
         - mycookbook (0.1.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...

       ================================================================================
       Recipe Compile Error in C:/Users/azure/AppData/Local/Temp/kitchen/cache/cookbooks/mycookbook/recipes/default.rb
       ================================================================================

       LoadError
       ---------
       Could not open library 'Chef.PowerShell.Wrapper.dll': The specified module could not be found.
```

Workaround/fix: copying the files msvcp140.dll and vcruntime140.dll to the c:\opscode\chef\embedded\bin folder resolves the issue
