### ISSUE TITLE
Windows share resource does not seem idempotent.

### ISSUE THREAD

**Issue by paul1994** [chef/chef#8879]
## Description
When using the windows share resource in a recipe it continues to converge after the first run.

## Chef Version

Chef Version
```
 chef -v
Chef Workstation version: 0.7.4
Chef Infra Client version: 15.1.36
Chef InSpec version: 4.7.3
Test Kitchen version: 2.2.5
Foodcritic version: 16.1.1
Cookstyle version: 5.0.0
```

## Platform Version

windows server 2012r2

## Replication Case

Created the following recipe 

```
windows_share 'Test_share' do 
  description 'A test share to test idempotency'
  path 'c:/chef'
  action :create
end
```
Used test kitchen to run the recipe on an aws 2012r2 ami.
using the following platform:
```
platforms:
  - name: windows-2012R2
    driver:
    image_search:
      owner-id: "801119661308"
      name: "amazon/Windows_Server-2012-R2_RTM-English-64Bit-Base*"
```
