### ISSUE TITLE
Resource cleanup broken Mac build verification

### ISSUE THREAD

**Issue by tas50** [chef/chef#9407]
## Description
After the resource cleanup our Mac build verification is now failing on master

## Chef Version
master

## Platform Version
Mac

## Stacktrace

Failures:

```

  1) Chef::Resource::Group group modify action when there is a group behaves like correct group management when the users exist when append is not set should set the group to to contain given members

     Failure/Error: user_to_create.run_action(:create)



     NoMethodError:

       mac_user[mnou5sdz] (dynamically defined) had an error: NoMethodError: undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd25715bce8>

     Shared Example Group: "correct group management" called from ./spec/functional/resource/group_spec.rb:413

     # ./lib/chef/provider/user/mac.rb:199:in `create_user'

     # ./lib/chef/provider/user.rb:122:in `block (2 levels) in <class:User>'

     # ./lib/chef/mixin/why_run.rb:51:in `add_action'

     # ./lib/chef/provider.rb:234:in `converge_by'

     # ./lib/chef/provider/user.rb:121:in `block in <class:User>'

     # (eval):2:in `block in action_create'

     # ./lib/chef/provider.rb:245:in `instance_eval'

     # ./lib/chef/provider.rb:245:in `compile_and_converge_action'

     # (eval):2:in `action_create'

     # ./lib/chef/provider.rb:189:in `run_action'

     # ./lib/chef/resource.rb:591:in `run_action'

     # ./spec/functional/resource/group_spec.rb:102:in `create_user'

     # ./spec/functional/resource/group_spec.rb:175:in `block (5 levels) in <top (required)>'

     # ./spec/functional/resource/group_spec.rb:173:in `each'

     # ./spec/functional/resource/group_spec.rb:173:in `block (4 levels) in <top (required)>'

     # ------------------

     # --- Caused by: ---

     # NoMethodError:

     #   undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd25715bce8>

     #   ./lib/chef/provider/user/mac.rb:199:in `create_user'



  2) Chef::Resource::Group group modify action when there is a group behaves like correct group management when the users exist when append is not set when group already contains some users should remove all existing users and only add the new users to the group

     Failure/Error: user_to_create.run_action(:create)



     NoMethodError:

       mac_user[mnou5sdz] (dynamically defined) had an error: NoMethodError: undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd255431438>

     Shared Example Group: "correct group management" called from ./spec/functional/resource/group_spec.rb:413

     # ./lib/chef/provider/user/mac.rb:199:in `create_user'

     # ./lib/chef/provider/user.rb:122:in `block (2 levels) in <class:User>'

     # ./lib/chef/mixin/why_run.rb:51:in `add_action'

     # ./lib/chef/provider.rb:234:in `converge_by'

     # ./lib/chef/provider/user.rb:121:in `block in <class:User>'

     # (eval):2:in `block in action_create'

     # ./lib/chef/provider.rb:245:in `instance_eval'

     # ./lib/chef/provider.rb:245:in `compile_and_converge_action'

     # (eval):2:in `action_create'

     # ./lib/chef/provider.rb:189:in `run_action'

     # ./lib/chef/resource.rb:591:in `run_action'

     # ./spec/functional/resource/group_spec.rb:102:in `create_user'

     # ./spec/functional/resource/group_spec.rb:175:in `block (5 levels) in <top (required)>'

     # ./spec/functional/resource/group_spec.rb:173:in `each'

     # ./spec/functional/resource/group_spec.rb:173:in `block (4 levels) in <top (required)>'

     # ------------------

     # --- Caused by: ---

     # NoMethodError:

     #   undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd255431438>

     #   ./lib/chef/provider/user/mac.rb:199:in `create_user'



  3) Chef::Resource::Group group modify action when there is a group behaves like correct group management when the users exist when append is set should add included members to the group

     Failure/Error: user_to_create.run_action(:create)



     NoMethodError:

       mac_user[mnou5sdz] (dynamically defined) had an error: NoMethodError: undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd251f43ac8>

     Shared Example Group: "correct group management" called from ./spec/functional/resource/group_spec.rb:413

     # ./lib/chef/provider/user/mac.rb:199:in `create_user'

     # ./lib/chef/provider/user.rb:122:in `block (2 levels) in <class:User>'

     # ./lib/chef/mixin/why_run.rb:51:in `add_action'

     # ./lib/chef/provider.rb:234:in `converge_by'

     # ./lib/chef/provider/user.rb:121:in `block in <class:User>'

     # (eval):2:in `block in action_create'

     # ./lib/chef/provider.rb:245:in `instance_eval'

     # ./lib/chef/provider.rb:245:in `compile_and_converge_action'

     # (eval):2:in `action_create'

     # ./lib/chef/provider.rb:189:in `run_action'

     # ./lib/chef/resource.rb:591:in `run_action'

     # ./spec/functional/resource/group_spec.rb:102:in `create_user'

     # ./spec/functional/resource/group_spec.rb:175:in `block (5 levels) in <top (required)>'

     # ./spec/functional/resource/group_spec.rb:173:in `each'

     # ./spec/functional/resource/group_spec.rb:173:in `block (4 levels) in <top (required)>'

     # ------------------

     # --- Caused by: ---

     # NoMethodError:

     #   undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd251f43ac8>

     #   ./lib/chef/provider/user/mac.rb:199:in `create_user'



  4) Chef::Resource::Group group modify action when there is a group behaves like correct group management when the users exist when append is set when group already contains some users should add the included users and remove excluded users

     Failure/Error: user_to_create.run_action(:create)



     NoMethodError:

       mac_user[mnou5sdz] (dynamically defined) had an error: NoMethodError: undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd253202b00>

     Shared Example Group: "correct group management" called from ./spec/functional/resource/group_spec.rb:413

     # ./lib/chef/provider/user/mac.rb:199:in `create_user'

     # ./lib/chef/provider/user.rb:122:in `block (2 levels) in <class:User>'

     # ./lib/chef/mixin/why_run.rb:51:in `add_action'

     # ./lib/chef/provider.rb:234:in `converge_by'

     # ./lib/chef/provider/user.rb:121:in `block in <class:User>'

     # (eval):2:in `block in action_create'

     # ./lib/chef/provider.rb:245:in `instance_eval'

     # ./lib/chef/provider.rb:245:in `compile_and_converge_action'

     # (eval):2:in `action_create'

     # ./lib/chef/provider.rb:189:in `run_action'

     # ./lib/chef/resource.rb:591:in `run_action'

     # ./spec/functional/resource/group_spec.rb:102:in `create_user'

     # ./spec/functional/resource/group_spec.rb:175:in `block (5 levels) in <top (required)>'

     # ./spec/functional/resource/group_spec.rb:173:in `each'

     # ./spec/functional/resource/group_spec.rb:173:in `block (4 levels) in <top (required)>'

     # ------------------

     # --- Caused by: ---

     # NoMethodError:

     #   undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd253202b00>

     #   ./lib/chef/provider/user/mac.rb:199:in `create_user'



  5) Chef::Resource::Group group manage action when there is a group behaves like correct group management when the users exist when append is not set should set the group to to contain given members

     Failure/Error: user_to_create.run_action(:create)



     NoMethodError:

       mac_user[mnou5sdz] (dynamically defined) had an error: NoMethodError: undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd25369cda0>

     Shared Example Group: "correct group management" called from ./spec/functional/resource/group_spec.rb:451

     # ./lib/chef/provider/user/mac.rb:199:in `create_user'

     # ./lib/chef/provider/user.rb:122:in `block (2 levels) in <class:User>'

     # ./lib/chef/mixin/why_run.rb:51:in `add_action'

     # ./lib/chef/provider.rb:234:in `converge_by'

     # ./lib/chef/provider/user.rb:121:in `block in <class:User>'

     # (eval):2:in `block in action_create'

     # ./lib/chef/provider.rb:245:in `instance_eval'

     # ./lib/chef/provider.rb:245:in `compile_and_converge_action'

     # (eval):2:in `action_create'

     # ./lib/chef/provider.rb:189:in `run_action'

     # ./lib/chef/resource.rb:591:in `run_action'

     # ./spec/functional/resource/group_spec.rb:102:in `create_user'

     # ./spec/functional/resource/group_spec.rb:175:in `block (5 levels) in <top (required)>'

     # ./spec/functional/resource/group_spec.rb:173:in `each'

     # ./spec/functional/resource/group_spec.rb:173:in `block (4 levels) in <top (required)>'

     # ------------------

     # --- Caused by: ---

     # NoMethodError:

     #   undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd25369cda0>

     #   ./lib/chef/provider/user/mac.rb:199:in `create_user'



  6) Chef::Resource::Group group manage action when there is a group behaves like correct group management when the users exist when append is not set when group already contains some users should remove all existing users and only add the new users to the group

     Failure/Error: user_to_create.run_action(:create)



     NoMethodError:

       mac_user[mnou5sdz] (dynamically defined) had an error: NoMethodError: undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd25692a830>

     Shared Example Group: "correct group management" called from ./spec/functional/resource/group_spec.rb:451

     # ./lib/chef/provider/user/mac.rb:199:in `create_user'

     # ./lib/chef/provider/user.rb:122:in `block (2 levels) in <class:User>'

     # ./lib/chef/mixin/why_run.rb:51:in `add_action'

     # ./lib/chef/provider.rb:234:in `converge_by'

     # ./lib/chef/provider/user.rb:121:in `block in <class:User>'

     # (eval):2:in `block in action_create'

     # ./lib/chef/provider.rb:245:in `instance_eval'

     # ./lib/chef/provider.rb:245:in `compile_and_converge_action'

     # (eval):2:in `action_create'

     # ./lib/chef/provider.rb:189:in `run_action'

     # ./lib/chef/resource.rb:591:in `run_action'

     # ./spec/functional/resource/group_spec.rb:102:in `create_user'

     # ./spec/functional/resource/group_spec.rb:175:in `block (5 levels) in <top (required)>'

     # ./spec/functional/resource/group_spec.rb:173:in `each'

     # ./spec/functional/resource/group_spec.rb:173:in `block (4 levels) in <top (required)>'

     # ------------------

     # --- Caused by: ---

     # NoMethodError:

     #   undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd25692a830>

     #   ./lib/chef/provider/user/mac.rb:199:in `create_user'



  7) Chef::Resource::Group group manage action when there is a group behaves like correct group management when the users exist when append is set should add included members to the group

     Failure/Error: user_to_create.run_action(:create)



     NoMethodError:

       mac_user[mnou5sdz] (dynamically defined) had an error: NoMethodError: undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd256bc1738>

     Shared Example Group: "correct group management" called from ./spec/functional/resource/group_spec.rb:451

     # ./lib/chef/provider/user/mac.rb:199:in `create_user'

     # ./lib/chef/provider/user.rb:122:in `block (2 levels) in <class:User>'

     # ./lib/chef/mixin/why_run.rb:51:in `add_action'

     # ./lib/chef/provider.rb:234:in `converge_by'

     # ./lib/chef/provider/user.rb:121:in `block in <class:User>'

     # (eval):2:in `block in action_create'

     # ./lib/chef/provider.rb:245:in `instance_eval'

     # ./lib/chef/provider.rb:245:in `compile_and_converge_action'

     # (eval):2:in `action_create'

     # ./lib/chef/provider.rb:189:in `run_action'

     # ./lib/chef/resource.rb:591:in `run_action'

     # ./spec/functional/resource/group_spec.rb:102:in `create_user'

     # ./spec/functional/resource/group_spec.rb:175:in `block (5 levels) in <top (required)>'

     # ./spec/functional/resource/group_spec.rb:173:in `each'

     # ./spec/functional/resource/group_spec.rb:173:in `block (4 levels) in <top (required)>'

     # ------------------

     # --- Caused by: ---

     # NoMethodError:

     #   undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd256bc1738>

     #   ./lib/chef/provider/user/mac.rb:199:in `create_user'



  8) Chef::Resource::Group group manage action when there is a group behaves like correct group management when the users exist when append is set when group already contains some users should add the included users and remove excluded users

     Failure/Error: user_to_create.run_action(:create)



     NoMethodError:

       mac_user[mnou5sdz] (dynamically defined) had an error: NoMethodError: undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd256e41760>

     Shared Example Group: "correct group management" called from ./spec/functional/resource/group_spec.rb:451

     # ./lib/chef/provider/user/mac.rb:199:in `create_user'

     # ./lib/chef/provider/user.rb:122:in `block (2 levels) in <class:User>'

     # ./lib/chef/mixin/why_run.rb:51:in `add_action'

     # ./lib/chef/provider.rb:234:in `converge_by'

     # ./lib/chef/provider/user.rb:121:in `block in <class:User>'

     # (eval):2:in `block in action_create'

     # ./lib/chef/provider.rb:245:in `instance_eval'

     # ./lib/chef/provider.rb:245:in `compile_and_converge_action'

     # (eval):2:in `action_create'

     # ./lib/chef/provider.rb:189:in `run_action'

     # ./lib/chef/resource.rb:591:in `run_action'

     # ./spec/functional/resource/group_spec.rb:102:in `create_user'

     # ./spec/functional/resource/group_spec.rb:175:in `block (5 levels) in <top (required)>'

     # ./spec/functional/resource/group_spec.rb:173:in `each'

     # ./spec/functional/resource/group_spec.rb:173:in `block (4 levels) in <top (required)>'

     # ------------------

     # --- Caused by: ---

     # NoMethodError:

     #   undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd256e41760>

     #   ./lib/chef/provider/user/mac.rb:199:in `create_user'



  9) Chef::Resource::Link when supported on platform is symbolic when the link destination is a file and the link already exists and is a symbolic link pointing somewhere else the :delete action does not delete the target file

     Got 0 failures and 2 other errors:



     9.1) Failure/Error: user(test_user).run_action(:create)



          NoMethodError:

            mac_user[test-link-user] (dynamically defined) had an error: NoMethodError: undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd2572507e8>

          # ./lib/chef/provider/user/mac.rb:199:in `create_user'

          # ./lib/chef/provider/user.rb:122:in `block (2 levels) in <class:User>'

          # ./lib/chef/mixin/why_run.rb:51:in `add_action'

          # ./lib/chef/provider.rb:234:in `converge_by'

          # ./lib/chef/provider/user.rb:121:in `block in <class:User>'

          # (eval):2:in `block in action_create'

          # ./lib/chef/provider.rb:245:in `instance_eval'

          # ./lib/chef/provider.rb:245:in `compile_and_converge_action'

          # (eval):2:in `action_create'

          # ./lib/chef/provider.rb:189:in `run_action'

          # ./lib/chef/resource.rb:591:in `run_action'

          # ./spec/functional/resource/link_spec.rb:350:in `block (7 levels) in <top (required)>'

          # ------------------

          # --- Caused by: ---

          # NoMethodError:

          #   undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd2572507e8>

          #   ./lib/chef/provider/user/mac.rb:199:in `create_user'



     9.2) Failure/Error: File.delete(@other_target)



          TypeError:

            no implicit conversion of nil into String

          # ./spec/functional/resource/link_spec.rb:366:in `delete'

          # ./spec/functional/resource/link_spec.rb:366:in `block (7 levels) in <top (required)>'



  10) Chef::Resource::Link when supported on platform is symbolic when the link destination is a file and the link already exists and is a symbolic link pointing somewhere else the :create action links to the target file

      Got 0 failures and 2 other errors:

      Shared Example Group: "create symbolic link succeeds" called from ./spec/functional/resource/link_spec.rb:368



      10.1) Failure/Error: user(test_user).run_action(:create)



            NoMethodError:

              mac_user[test-link-user] (dynamically defined) had an error: NoMethodError: undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd255379950>

            # ./lib/chef/provider/user/mac.rb:199:in `create_user'

            # ./lib/chef/provider/user.rb:122:in `block (2 levels) in <class:User>'

            # ./lib/chef/mixin/why_run.rb:51:in `add_action'

            # ./lib/chef/provider.rb:234:in `converge_by'

            # ./lib/chef/provider/user.rb:121:in `block in <class:User>'

            # (eval):2:in `block in action_create'

            # ./lib/chef/provider.rb:245:in `instance_eval'

            # ./lib/chef/provider.rb:245:in `compile_and_converge_action'

            # (eval):2:in `action_create'

            # ./lib/chef/provider.rb:189:in `run_action'

            # ./lib/chef/resource.rb:591:in `run_action'

            # ./spec/functional/resource/link_spec.rb:350:in `block (7 levels) in <top (required)>'

            # ------------------

            # --- Caused by: ---

            # NoMethodError:

            #   undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd255379950>

            #   ./lib/chef/provider/user/mac.rb:199:in `create_user'



      10.2) Failure/Error: File.delete(@other_target)



            TypeError:

              no implicit conversion of nil into String

            # ./spec/functional/resource/link_spec.rb:366:in `delete'

            # ./spec/functional/resource/link_spec.rb:366:in `block (7 levels) in <top (required)>'



  11) Chef::Resource::Link when supported on platform is symbolic when the link destination is a file and the link already exists and is a symbolic link pointing somewhere else the :create action marks the resource updated

      Got 0 failures and 2 other errors:

      Shared Example Group: "create symbolic link succeeds" called from ./spec/functional/resource/link_spec.rb:368



      11.1) Failure/Error: user(test_user).run_action(:create)



            NoMethodError:

              mac_user[test-link-user] (dynamically defined) had an error: NoMethodError: undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd2542c0410>

            # ./lib/chef/provider/user/mac.rb:199:in `create_user'

            # ./lib/chef/provider/user.rb:122:in `block (2 levels) in <class:User>'

            # ./lib/chef/mixin/why_run.rb:51:in `add_action'

            # ./lib/chef/provider.rb:234:in `converge_by'

            # ./lib/chef/provider/user.rb:121:in `block in <class:User>'

            # (eval):2:in `block in action_create'

            # ./lib/chef/provider.rb:245:in `instance_eval'

            # ./lib/chef/provider.rb:245:in `compile_and_converge_action'

            # (eval):2:in `action_create'

            # ./lib/chef/provider.rb:189:in `run_action'

            # ./lib/chef/resource.rb:591:in `run_action'

            # ./spec/functional/resource/link_spec.rb:350:in `block (7 levels) in <top (required)>'

            # ------------------

            # --- Caused by: ---

            # NoMethodError:

            #   undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd2542c0410>

            #   ./lib/chef/provider/user/mac.rb:199:in `create_user'



      11.2) Failure/Error: File.delete(@other_target)



            TypeError:

              no implicit conversion of nil into String

            # ./spec/functional/resource/link_spec.rb:366:in `delete'

            # ./spec/functional/resource/link_spec.rb:366:in `block (7 levels) in <top (required)>'



  12) Chef::Resource::Link when supported on platform is symbolic when the link destination is a file and the link already exists and is a symbolic link pointing somewhere else the :create action logs that it created

      Got 0 failures and 2 other errors:

      Shared Example Group: "create symbolic link succeeds" called from ./spec/functional/resource/link_spec.rb:368



      12.1) Failure/Error: user(test_user).run_action(:create)



            NoMethodError:

              mac_user[test-link-user] (dynamically defined) had an error: NoMethodError: undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd253428a10>

            # ./lib/chef/provider/user/mac.rb:199:in `create_user'

            # ./lib/chef/provider/user.rb:122:in `block (2 levels) in <class:User>'

            # ./lib/chef/mixin/why_run.rb:51:in `add_action'

            # ./lib/chef/provider.rb:234:in `converge_by'

            # ./lib/chef/provider/user.rb:121:in `block in <class:User>'

            # (eval):2:in `block in action_create'

            # ./lib/chef/provider.rb:245:in `instance_eval'

            # ./lib/chef/provider.rb:245:in `compile_and_converge_action'

            # (eval):2:in `action_create'

            # ./lib/chef/provider.rb:189:in `run_action'

            # ./lib/chef/resource.rb:591:in `run_action'

            # ./spec/functional/resource/link_spec.rb:350:in `block (7 levels) in <top (required)>'

            # ------------------

            # --- Caused by: ---

            # NoMethodError:

            #   undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd253428a10>

            #   ./lib/chef/provider/user/mac.rb:199:in `create_user'



      12.2) Failure/Error: File.delete(@other_target)



            TypeError:

              no implicit conversion of nil into String

            # ./spec/functional/resource/link_spec.rb:366:in `delete'

            # ./spec/functional/resource/link_spec.rb:366:in `block (7 levels) in <top (required)>'



  13) Chef::Resource::Link when supported on platform is symbolic when the link destination is a file and the link already exists and is a symbolic link pointing somewhere else the :delete action deletes the file

      Got 0 failures and 2 other errors:

      Shared Example Group: "delete succeeds" called from ./spec/functional/resource/link_spec.rb:369



      13.1) Failure/Error: user(test_user).run_action(:create)



            NoMethodError:

              mac_user[test-link-user] (dynamically defined) had an error: NoMethodError: undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd25377fc18>

            # ./lib/chef/provider/user/mac.rb:199:in `create_user'

            # ./lib/chef/provider/user.rb:122:in `block (2 levels) in <class:User>'

            # ./lib/chef/mixin/why_run.rb:51:in `add_action'

            # ./lib/chef/provider.rb:234:in `converge_by'

            # ./lib/chef/provider/user.rb:121:in `block in <class:User>'

            # (eval):2:in `block in action_create'

            # ./lib/chef/provider.rb:245:in `instance_eval'

            # ./lib/chef/provider.rb:245:in `compile_and_converge_action'

            # (eval):2:in `action_create'

            # ./lib/chef/provider.rb:189:in `run_action'

            # ./lib/chef/resource.rb:591:in `run_action'

            # ./spec/functional/resource/link_spec.rb:350:in `block (7 levels) in <top (required)>'

            # ------------------

            # --- Caused by: ---

            # NoMethodError:

            #   undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd25377fc18>

            #   ./lib/chef/provider/user/mac.rb:199:in `create_user'



      13.2) Failure/Error: File.delete(@other_target)



            TypeError:

              no implicit conversion of nil into String

            # ./spec/functional/resource/link_spec.rb:366:in `delete'

            # ./spec/functional/resource/link_spec.rb:366:in `block (7 levels) in <top (required)>'



  14) Chef::Resource::Link when supported on platform is symbolic when the link destination is a file and the link already exists and is a symbolic link pointing somewhere else the :delete action marks the resource updated

      Got 0 failures and 2 other errors:

      Shared Example Group: "delete succeeds" called from ./spec/functional/resource/link_spec.rb:369



      14.1) Failure/Error: user(test_user).run_action(:create)



            NoMethodError:

              mac_user[test-link-user] (dynamically defined) had an error: NoMethodError: undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd256a61ed8>

            # ./lib/chef/provider/user/mac.rb:199:in `create_user'

            # ./lib/chef/provider/user.rb:122:in `block (2 levels) in <class:User>'

            # ./lib/chef/mixin/why_run.rb:51:in `add_action'

            # ./lib/chef/provider.rb:234:in `converge_by'

            # ./lib/chef/provider/user.rb:121:in `block in <class:User>'

            # (eval):2:in `block in action_create'

            # ./lib/chef/provider.rb:245:in `instance_eval'

            # ./lib/chef/provider.rb:245:in `compile_and_converge_action'

            # (eval):2:in `action_create'

            # ./lib/chef/provider.rb:189:in `run_action'

            # ./lib/chef/resource.rb:591:in `run_action'

            # ./spec/functional/resource/link_spec.rb:350:in `block (7 levels) in <top (required)>'

            # ------------------

            # --- Caused by: ---

            # NoMethodError:

            #   undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd256a61ed8>

            #   ./lib/chef/provider/user/mac.rb:199:in `create_user'



      14.2) Failure/Error: File.delete(@other_target)



            TypeError:

              no implicit conversion of nil into String

            # ./spec/functional/resource/link_spec.rb:366:in `delete'

            # ./spec/functional/resource/link_spec.rb:366:in `block (7 levels) in <top (required)>'



  15) Chef::Resource::Link when supported on platform is symbolic when the link destination is a file and the link already exists and is a symbolic link pointing somewhere else the :delete action logs that it deleted

      Got 0 failures and 2 other errors:

      Shared Example Group: "delete succeeds" called from ./spec/functional/resource/link_spec.rb:369



      15.1) Failure/Error: user(test_user).run_action(:create)



            NoMethodError:

              mac_user[test-link-user] (dynamically defined) had an error: NoMethodError: undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd256d20430>

            # ./lib/chef/provider/user/mac.rb:199:in `create_user'

            # ./lib/chef/provider/user.rb:122:in `block (2 levels) in <class:User>'

            # ./lib/chef/mixin/why_run.rb:51:in `add_action'

            # ./lib/chef/provider.rb:234:in `converge_by'

            # ./lib/chef/provider/user.rb:121:in `block in <class:User>'

            # (eval):2:in `block in action_create'

            # ./lib/chef/provider.rb:245:in `instance_eval'

            # ./lib/chef/provider.rb:245:in `compile_and_converge_action'

            # (eval):2:in `action_create'

            # ./lib/chef/provider.rb:189:in `run_action'

            # ./lib/chef/resource.rb:591:in `run_action'

            # ./spec/functional/resource/link_spec.rb:350:in `block (7 levels) in <top (required)>'

            # ------------------

            # --- Caused by: ---

            # NoMethodError:

            #   undefined method `group' for #<Chef::Provider::User::MacUser:0x00007fd256d20430>

            #   ./lib/chef/provider/user/mac.rb:199:in `create_user'



      15.2) Failure/Error: File.delete(@other_target)



            TypeError:

              no implicit conversion of nil into String

            # ./spec/functional/resource/link_spec.rb:366:in `delete'

            # ./spec/functional/resource/link_spec.rb:366:in `block (7 levels) in <top (required)>'

```
