### ISSUE TITLE
Unexpected behavior converting arrays and symbols from YAML

### ISSUE THREAD

**Issue by ChefRycar** [chef/chef#9766]
## Description
When converting a YAML recipe that contains an array or symbols, they appear to convert into double-quoted strings rather than the expected data types. (see replication case for details)

## Chef Version

Tested on `16.0.244` & `16.0.259`

## Platform Version

Assume this is platform independent, but tested within default centos-7 vagrant VM in a TK instance.

## Replication Case

* Create a YAML recipe with the following content:

```
---
resources:
  - type: "package"
    name: "httpd"
  - type: "service"
    name: "httpd"
    action:
      - enable
      - start
```

* Run `knife yaml convert FILENAME.yml`

* Expected content for the service resource:

```
service "httpd" do
  action [:enable, :start]
end
```

* Actual content of generated resource:

```
service "httpd" do
  action "["enable", "start"]"
end
```

## Client Output

N/A

## Stacktrace

N/A

**Comment by ChefRycar** [comment]
It occurred that this could be an edge case for arrays *of* symbols specifically (thanks for suggesting, @phiggins!), so I ran a quick follow-up test.

I tested both a symbol by itself, and an array of strings, and noted the same behavior. For posterity, here's version two before/after (and, yup, know my syntax is wrong anyway on the second one, but just wanted to test conversion in the abstract. :-) )

Source YAML:
```
---
resources:
  - type: "package"
    name: "httpd"
    action: install
  - type: "service"
    name: "httpd"
    action:
      - "enable"
      - "start"
```

Converted file:
```
package "httpd" do
  action "install"
end

service "httpd" do
  action "["enable", "start"]"
end
```
