### ISSUE TITLE
Add new 'yaml_file' resource

### ISSUE THREAD

**Issue by mattray** [chef/chef#9912]
A resource for writing out YAML files would replace many of the use of templates or the `file` resource to write these out from strings. It would be an extension of the `file` resource, replacing the `content` with a hash and keeping all the existing properties.

## Motivation

As a user, I want to pass a hash of attributes to a `yaml_file` resource and have it render them appropriately.

## Specification

```
a = {
    'golf': 'hotel',
    'kilo': ['lima', 'mike', 'november'],
    'india': {
        'juliett': true
        },
    'alpha': {
        'charlie': 'delta',
        'bravo': 10,
        },
    'echo': 'foxtrot'
    }

yaml_file '/tmp/file.yaml do
    content a
end
```

produces the file `/tmp/file.yaml`
```
---
golf: hotel
kilo:
- lima
- mike
- november
india:
  juliett: true
alpha:
  charlie: delta
  bravo: 10
echo: foxtrot
```

```
